--SQL UP SCRIPT

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'BankAccount' AND COLUMN_NAME = 'Title'
)
BEGIN
    ALTER TABLE dbo.BankAccount
    ADD Title NVARCHAR(100) null;
END