//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBang.App.Cloud.ERP.Accounting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigBang.App.Cloud.ERP.Accounting.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش پرداخت.
        /// </summary>
        internal static string AccountTree_AdvancePayment {
            get {
                return ResourceManager.GetString("AccountTree_AdvancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش دریافت.
        /// </summary>
        internal static string AccountTree_AdvanceReceipt {
            get {
                return ResourceManager.GetString("AccountTree_AdvanceReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارایی.
        /// </summary>
        internal static string AccountTree_Assets {
            get {
                return ResourceManager.GetString("AccountTree_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک.
        /// </summary>
        internal static string AccountTree_Bank {
            get {
                return ResourceManager.GetString("AccountTree_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید.
        /// </summary>
        internal static string AccountTree_Buy {
            get {
                return ResourceManager.GetString("AccountTree_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه.
        /// </summary>
        internal static string AccountTree_Expense {
            get {
                return ResourceManager.GetString("AccountTree_Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غذا.
        /// </summary>
        internal static string AccountTree_Food {
            get {
                return ResourceManager.GetString("AccountTree_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صندوق.
        /// </summary>
        internal static string AccountTree_Fund {
            get {
                return ResourceManager.GetString("AccountTree_Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهای تمام شده کالای فروش رفته.
        /// </summary>
        internal static string AccountTree_GeneralCostOfProductSold {
            get {
                return ResourceManager.GetString("AccountTree_GeneralCostOfProductSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرمایه.
        /// </summary>
        internal static string AccountTree_GeneralEquity {
            get {
                return ResourceManager.GetString("AccountTree_GeneralEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدهی.
        /// </summary>
        internal static string AccountTree_Liabilities {
            get {
                return ResourceManager.GetString("AccountTree_Liabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدهی به دیگران.
        /// </summary>
        internal static string AccountTree_LiabilitiesToOthers {
            get {
                return ResourceManager.GetString("AccountTree_LiabilitiesToOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت.
        /// </summary>
        internal static string AccountTree_Payment {
            get {
                return ResourceManager.GetString("AccountTree_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی کالا.
        /// </summary>
        internal static string AccountTree_ProductInventory {
            get {
                return ResourceManager.GetString("AccountTree_ProductInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروش کالا.
        /// </summary>
        internal static string AccountTree_ProductSell {
            get {
                return ResourceManager.GetString("AccountTree_ProductSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب از دیگران.
        /// </summary>
        internal static string AccountTree_ReceivableFromOthers {
            get {
                return ResourceManager.GetString("AccountTree_ReceivableFromOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره.
        /// </summary>
        internal static string AccountTree_Rent {
            get {
                return ResourceManager.GetString("AccountTree_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درآمد.
        /// </summary>
        internal static string AccountTree_Revenue {
            get {
                return ResourceManager.GetString("AccountTree_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخت حساب.
        /// </summary>
        internal static string AccountTree_Root {
            get {
                return ResourceManager.GetString("AccountTree_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق.
        /// </summary>
        internal static string AccountTree_Salary {
            get {
                return ResourceManager.GetString("AccountTree_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارائه خدمات.
        /// </summary>
        internal static string AccountTree_ServicesProvided {
            get {
                return ResourceManager.GetString("AccountTree_ServicesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهای تمام شده کالای فروش رفته.
        /// </summary>
        internal static string AccountTree_SubsidiaryCostOfProductSold {
            get {
                return ResourceManager.GetString("AccountTree_SubsidiaryCostOfProductSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرمایه.
        /// </summary>
        internal static string AccountTree_SubsidiaryEquity {
            get {
                return ResourceManager.GetString("AccountTree_SubsidiaryEquity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حمل و نقل.
        /// </summary>
        internal static string AccountTree_Transport {
            get {
                return ResourceManager.GetString("AccountTree_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشت.
        /// </summary>
        internal static string AccountTree_Withdraw {
            get {
                return ResourceManager.GetString("AccountTree_Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب.
        /// </summary>
        internal static string Entity_Account {
            get {
                return ResourceManager.GetString("Entity_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب بانکی.
        /// </summary>
        internal static string Entity_BankAccount {
            get {
                return ResourceManager.GetString("Entity_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کار.
        /// </summary>
        internal static string Entity_Bussiness {
            get {
                return ResourceManager.GetString("Entity_Bussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره مالی.
        /// </summary>
        internal static string Entity_FiscalPeriod {
            get {
                return ResourceManager.GetString("Entity_FiscalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحب کسب و کار.
        /// </summary>
        internal static string Entity_Owner {
            get {
                return ResourceManager.GetString("Entity_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص.
        /// </summary>
        internal static string Entity_PersonAccount {
            get {
                return ResourceManager.GetString("Entity_PersonAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا.
        /// </summary>
        internal static string Entity_Product {
            get {
                return ResourceManager.GetString("Entity_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند.
        /// </summary>
        internal static string Entity_Voucher {
            get {
                return ResourceManager.GetString("Entity_Voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب وارد شده برای تمپلیت مورد نظر معتبر نیست.
        /// </summary>
        internal static string Error_AccountForTemplateIsNotValid {
            get {
                return ResourceManager.GetString("Error_AccountForTemplateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماهیت حساب معتبر نیست.
        /// </summary>
        internal static string Error_AccountNatureIsInvalid {
            get {
                return ResourceManager.GetString("Error_AccountNatureIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد آرتیکل های وارد شده معتبر نیست.
        /// </summary>
        internal static string Error_ArticlesAreNotValid {
            get {
                return ResourceManager.GetString("Error_ArticlesAreNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایپ آرتیکل وارد شده معتبر نیست.
        /// </summary>
        internal static string Error_ArticleTypeIsNotValid {
            get {
                return ResourceManager.GetString("Error_ArticleTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی حساب بانکی کافی نیست.
        /// </summary>
        internal static string Error_BankAccountBalanceIsNotEnough {
            get {
                return ResourceManager.GetString("Error_BankAccountBalanceIsNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب بانک وجود ندارد.
        /// </summary>
        internal static string Error_BankAccountNotExist {
            get {
                return ResourceManager.GetString("Error_BankAccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در خرید اقساطی بدون هزینه حمل، نباید پولی از حساب بانکی کسر شود.
        /// </summary>
        internal static string Error_BankAccountShouldNotInvolved {
            get {
                return ResourceManager.GetString("Error_BankAccountShouldNotInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در خرید کالا با برداشت از بانک، پولی که از بانک برداشت میشود باید با مجموع کالاهای خریداری شده و هزینه ی حمل (در صورت وجود) برابر باشد.
        /// </summary>
        internal static string Error_BankAccountWithdrawShouldEqualToTotalProductsAmount {
            get {
                return ResourceManager.GetString("Error_BankAccountWithdrawShouldEqualToTotalProductsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در خرید اقساطی با هزینه حمل، پولی که از بانک برداشت میشود باید مساوی هزینه حمل باشد.
        /// </summary>
        internal static string Error_BankAccountWithdrawShouldEqualToTransportAmount {
            get {
                return ResourceManager.GetString("Error_BankAccountWithdrawShouldEqualToTransportAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در فروش نسیه، حساب بانک نباید وجود داشته باشد.
        /// </summary>
        internal static string Error_BankNotExistInCreditSale {
            get {
                return ResourceManager.GetString("Error_BankNotExistInCreditSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحب کسب و کار قابل حذف نیست.
        /// </summary>
        internal static string Error_BuisnessOwnerCannotBeDeleted {
            get {
                return ResourceManager.GetString("Error_BuisnessOwnerCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش صاحب کسب و کار را نمیتوان به شخص دیگری نسبت داد.
        /// </summary>
        internal static string Error_CannotAssigeBussinessOwnerRoleToAnotherPerson {
            get {
                return ResourceManager.GetString("Error_CannotAssigeBussinessOwnerRoleToAnotherPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف نقش صاحب کسب و کار برای صاحب کسب و کار وجود ندارد.
        /// </summary>
        internal static string Error_CannotRemoveBussinessOwnerRoleForOwnerPersonAccount {
            get {
                return ResourceManager.GetString("Error_CannotRemoveBussinessOwnerRoleForOwnerPersonAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد پولی وارد شده معتبر نیست.
        /// </summary>
        internal static string Error_CurencyIsNotValid {
            get {
                return ResourceManager.GetString("Error_CurencyIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سند باید در بازه دوره مالی باشد.
        /// </summary>
        internal static string Error_EffectiveDateShouldBeInRangeOfFiscalPeriodDate {
            get {
                return ResourceManager.GetString("Error_EffectiveDateShouldBeInRangeOfFiscalPeriodDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل ثبت سند {0} قابل حذف نیست.
        /// </summary>
        internal static string Error_EntityCantBeDeletedDueToHavingVoucher {
            get {
                return ResourceManager.GetString("Error_EntityCantBeDeletedDueToHavingVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} یافت نشد.
        /// </summary>
        internal static string Error_EntityNotFound {
            get {
                return ResourceManager.GetString("Error_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} دقیقا باید {1} رقم باشد.
        /// </summary>
        internal static string Error_ExactLengthShouldBe {
            get {
                return ResourceManager.GetString("Error_ExactLengthShouldBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت واحد ضربدر تعداد باید مساوی مبلغ باشد.
        /// </summary>
        internal static string Error_FeeMultipliedByQuantityShouldEqualToAmount {
            get {
                return ResourceManager.GetString("Error_FeeMultipliedByQuantityShouldEqualToAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد کردن {0} اجباری است.
        /// </summary>
        internal static string Error_FieldRequired {
            get {
                return ResourceManager.GetString("Error_FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ از باید کوچکتر مساوی تاریخ تا باشد.
        /// </summary>
        internal static string Error_FromDateToDateIsNotValid {
            get {
                return ResourceManager.GetString("Error_FromDateToDateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توزیع هزینه حمل بر روی کالاها به درستی انجام نشده است.
        /// </summary>
        internal static string Error_IncorrectDistributionTransportCalculation {
            get {
                return ResourceManager.GetString("Error_IncorrectDistributionTransportCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب وارد شده قابلیت ثبت سند دستی را ندارد.
        /// </summary>
        internal static string Error_InvalidAccountForCustomVoucher {
            get {
                return ResourceManager.GetString("Error_InvalidAccountForCustomVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ حساب پرداختنی باید برابر با مجموع قیمت خرید خود کالاها باشد .
        /// </summary>
        internal static string Error_LiablitiesToOthersShouldEqualToTotalProductsAmount {
            get {
                return ResourceManager.GetString("Error_LiablitiesToOthersShouldEqualToTotalProductsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع حساب تفصیلی معتبر نیست.
        /// </summary>
        internal static string Error_LookUpTypeIsNotValid {
            get {
                return ResourceManager.GetString("Error_LookUpTypeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} حداکثر باید {1} کاراکتر باشد.
        /// </summary>
        internal static string Error_MaximumLengthShouldBe {
            get {
                return ResourceManager.GetString("Error_MaximumLengthShouldBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل باید 11 رقم باشد.
        /// </summary>
        internal static string Error_MobileNumberShouldBeElevenDigits {
            get {
                return ResourceManager.GetString("Error_MobileNumberShouldBeElevenDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا تکراری است.
        /// </summary>
        internal static string Error_ProducExists {
            get {
                return ResourceManager.GetString("Error_ProducExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی کالا کمتر از میزان درخواست شده است.
        /// </summary>
        internal static string Error_ProductIsNotInStock {
            get {
                return ResourceManager.GetString("Error_ProductIsNotInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ حساب دریافتنی بدهکار با مبلغ حساب دریافتنی بستانکار باید برابر باشد.
        /// </summary>
        internal static string Error_ReceivableFromOthersDebitShouldBeEqualToReceivableFromOthersCredit {
            get {
                return ResourceManager.GetString("Error_ReceivableFromOthersDebitShouldBeEqualToReceivableFromOthersCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ حساب دریافتنی باید با مبلغ واریز به بانک برابر باشد.
        /// </summary>
        internal static string Error_ReceivableFromOthersShouldEqualToDepositToBank {
            get {
                return ResourceManager.GetString("Error_ReceivableFromOthersShouldEqualToDepositToBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ حساب دریافتنی باید با مجموع قیمت فروش کالاها برابر باشد.
        /// </summary>
        internal static string Error_ReceivableFromOthersShouldEqualToTotalProductsAmount {
            get {
                return ResourceManager.GetString("Error_ReceivableFromOthersShouldEqualToTotalProductsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بزرگتر از {1} باشد.
        /// </summary>
        internal static string Error_ShouldBeGreaterThan {
            get {
                return ResourceManager.GetString("Error_ShouldBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نباید مقدار داشته باشد.
        /// </summary>
        internal static string Error_ShouldBeNull {
            get {
                return ResourceManager.GetString("Error_ShouldBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نباید خالی باشد.
        /// </summary>
        internal static string Error_ShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("Error_ShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نباید منفی باشد.
        /// </summary>
        internal static string Error_ShouldNotBeNegative {
            get {
                return ResourceManager.GetString("Error_ShouldNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید مقدار داشته باشد.
        /// </summary>
        internal static string Error_ShouldNotBeNull {
            get {
                return ResourceManager.GetString("Error_ShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب سازی فقط میتواند براساس تعداد کالا، مبلغ فروش،مبلغ تمام شده کالا و مابه التفاوت مبلغ تمام شده کالا و مبلغ فروش باشد.
        /// </summary>
        internal static string Error_SortByHaveToBeSellQuantity_SellAmount_CostAmountAndDifferenceAmount {
            get {
                return ResourceManager.GetString("Error_SortByHaveToBeSellQuantity,SellAmount,CostAmountAndDifferenceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب سازی فقط می تواند بر اساس مجموع بدهکارها، مجموع بستانکارها یا مابه التفاوت مجموع بدهکارها و بستانکارها باشد.
        /// </summary>
        internal static string Error_SortByHaveToBeTotalDebit_TotalCredit_Difference {
            get {
                return ResourceManager.GetString("Error_SortByHaveToBeTotalDebit_TotalCredit_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب سازی فقط میتواند صعودی یا نزولی باشد.
        /// </summary>
        internal static string Error_SortDirectionHaveToBeDescendingOrAscending {
            get {
                return ResourceManager.GetString("Error_SortDirectionHaveToBeDescendingOrAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ بهای تمام شده کالای فروش رفته باید با مجموع مبلغ موجودی کالا برابر باشد.
        /// </summary>
        internal static string Error_SubsidiaryCostOfProductSoldShouldEqualToTotalProductAmount {
            get {
                return ResourceManager.GetString("Error_SubsidiaryCostOfProductSoldShouldEqualToTotalProductAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع مبالغ بدهکار و بستانکار باید برابر باشد.
        /// </summary>
        internal static string Error_SumOfDebitAndCreditShouldBeEqual {
            get {
                return ResourceManager.GetString("Error_SumOfDebitAndCreditShouldBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمپلیت سند وارد شده معتبر نیست.
        /// </summary>
        internal static string Error_TemplateValueIsNotValid {
            get {
                return ResourceManager.GetString("Error_TemplateValueIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشت از بانک باید با پیش پرداخت برابر باشد.
        /// </summary>
        internal static string Error_WhitdrawFromBankShouldBeEqualToAdvancePayment {
            get {
                return ResourceManager.GetString("Error_WhitdrawFromBankShouldBeEqualToAdvancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کانفیگ فایل نامعتبر است.
        /// </summary>
        internal static string File_InvalidFileConfig {
            get {
                return ResourceManager.GetString("File_InvalidFileConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل نامتعبر است.
        /// </summary>
        internal static string File_InvalidFileFormat {
            get {
                return ResourceManager.GetString("File_InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل نامعتبر است.
        /// </summary>
        internal static string File_InvalidFileName {
            get {
                return ResourceManager.GetString("File_InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل سایز میتواند{0}  و حداکثر میتواند {1} باشد.
        /// </summary>
        internal static string File_InvalidFileSizeRange {
            get {
                return ResourceManager.GetString("File_InvalidFileSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه حساب.
        /// </summary>
        internal static string Label_AccountId {
            get {
                return ResourceManager.GetString("Label_AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        internal static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی حساب.
        /// </summary>
        internal static string Label_Balance {
            get {
                return ResourceManager.GetString("Label_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک.
        /// </summary>
        internal static string Label_Bank {
            get {
                return ResourceManager.GetString("Label_Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کسب و کار.
        /// </summary>
        internal static string Label_BusinessName {
            get {
                return ResourceManager.GetString("Label_BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت خرید.
        /// </summary>
        internal static string Label_BuyPrice {
            get {
                return ResourceManager.GetString("Label_BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت.
        /// </summary>
        internal static string Label_CardNumber {
            get {
                return ResourceManager.GetString("Label_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت واحد.
        /// </summary>
        internal static string Label_Fee {
            get {
                return ResourceManager.GetString("Label_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل.
        /// </summary>
        internal static string Label_File {
            get {
                return ResourceManager.GetString("Label_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل.
        /// </summary>
        internal static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام .
        /// </summary>
        internal static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارنده حساب.
        /// </summary>
        internal static string Label_HolderName {
            get {
                return ResourceManager.GetString("Label_HolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی .
        /// </summary>
        internal static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تفصیلی.
        /// </summary>
        internal static string Label_Lookup {
            get {
                return ResourceManager.GetString("Label_Lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        internal static string Label_MobileNumber {
            get {
                return ResourceManager.GetString("Label_MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صاحب کسب و کار.
        /// </summary>
        internal static string Label_OwnerName {
            get {
                return ResourceManager.GetString("Label_OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره صفحه.
        /// </summary>
        internal static string Label_PageNumber {
            get {
                return ResourceManager.GetString("Label_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد آیتم های صفحه.
        /// </summary>
        internal static string Label_PageSize {
            get {
                return ResourceManager.GetString("Label_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        internal static string Label_PersonRole {
            get {
                return ResourceManager.GetString("Label_PersonRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کالا.
        /// </summary>
        internal static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        internal static string Label_Quantity {
            get {
                return ResourceManager.GetString("Label_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا.
        /// </summary>
        internal static string Label_ShebaNumber {
            get {
                return ResourceManager.GetString("Label_ShebaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی کالا.
        /// </summary>
        internal static string Label_Stock {
            get {
                return ResourceManager.GetString("Label_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت پیشنهادی فروش.
        /// </summary>
        internal static string Label_SuggestedSellPrice {
            get {
                return ResourceManager.GetString("Label_SuggestedSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        internal static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آرتیکل سند.
        /// </summary>
        internal static string Label_VoucherArticles {
            get {
                return ResourceManager.GetString("Label_VoucherArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات سند.
        /// </summary>
        internal static string Label_VoucherDescription {
            get {
                return ResourceManager.GetString("Label_VoucherDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ سند.
        /// </summary>
        internal static string Label_VoucherEffectiveDate {
            get {
                return ResourceManager.GetString("Label_VoucherEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال مالی {0}.
        /// </summary>
        internal static string Title_FiscalYear {
            get {
                return ResourceManager.GetString("Title_FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجود در انبار.
        /// </summary>
        internal static string VoucherTitle_AddProduct {
            get {
                return ResourceManager.GetString("VoucherTitle_AddProduct", resourceCulture);
            }
        }
    }
}
