IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='PersonAccount')
DROP TABLE [dbo].[PersonAccount]
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='BankAccount')
DROP TABLE [dbo].[BankAccount]
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Article')
DROP TABLE [dbo].[Article]
GO 

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Voucher')
DROP TABLE [dbo].[Voucher]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Account')
DROP TABLE [dbo].[Account]
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='FiscalPeriod')
DROP TABLE [dbo].[FiscalPeriod]
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Business')
DROP TABLE [dbo].[Business]
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Owner')
DROP TABLE [dbo].[Owner]
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VoucherTemplate')
DROP TABLE [dbo].[VoucherTemplate]

GO